
- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
#    guest_name: "10.1.36.212-hpecp12"    
#    time: "{{ lookup('pipe', 'date -d \"0 day ago\" +\"%Y%m%d\"') }}"
#    time: "{{ lookup('pipe', 'date +%d\') }}"
     time: "{{ ansible_date_time.weekday }}"
     week: "{{ ansible_date_time.weeknumber }}"
     number: "{{ week|int % 2 }}"



  tasks:
    - name: Gather all registered virtual machines
      vmware_vm_info:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        vm_type: vm
        validate_certs: False
#      delegate_to: localhost
      register: vminfo

#    - debug: msg="{{ item.guest_name }}"  
#      with_items: "{{ vminfo.virtual_machines }}"




    - name: Remove a snapshot before creating an new
      vmware_guest_snapshot:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        datacenter: '{{  lookup("env", "datacenter_name") }}'
        folder: "/{{ datacenter_name }}/vm/"
        name: "{{ item.guest_name }}"
        state: absent
        snapshot_name: snap-{{numbler}}-{{ time }}
        validate_certs: False
      ignore_errors: yes
#      delegate_to: localhost
      with_items: "{{ vminfo.virtual_machines }}"

    - name: Create a snapshot
      vmware_guest_snapshot:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        datacenter: '{{  lookup("env", "datacenter_name") }}'
        folder: "/{{ datacenter_name }}/vm/"
        name: "{{ item.guest_name }}"
        state: present
        memory_dump: no
        snapshot_name: snap1-{{ time }}
        description: snap1_description
        validate_certs: False
      ignore_errors: yes
#      delegate_to: localhost
      with_items: "{{ vminfo.virtual_machines }}"
