
- hosts: localhost
  gather_facts: no
  vars:
#    guest_name: "10.1.36.212-hpecp12"    
#    time: "{{ lookup('pipe', 'date -d \"0 day ago\" +\"%Y%m%d\"') }}"
    time: "{{ lookup('pipe', 'date +%d\') }}"




  tasks:
    - name: Gather all registered virtual machines
      vmware_vm_info:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        vm_type: vm
        validate_certs: False
      delegate_to: localhost
      register: vminfo

#    - debug: msg="{{ item.guest_name }}"  
#      with_items: "{{ vminfo.virtual_machines }}"

