

- hosts: localhost
  connection: local
  gather_facts: yes
  vars:
#    guest_name: "10.1.36.212-hpecp12"    
#    time: "{{ lookup('pipe', 'date -d \"0 day ago\" +\"%Y%m%d\"') }}"
#    time: "{{ lookup('pipe', 'date +%d\') }}"
     time: "{{ ansible_date_time.weekday }}"
     week: "{{ ansible_date_time.weeknumber }}"
     number: "{{ week|int % 2 }}"
     week1: "{{ week|int + 1}}"
     number1: "{{ week1|int % 2 }}"



  tasks:
#    - name: Install pip module jmespath
#      pip:
#        name: jmespath
#        umask: "0022"
#        extra_args: "--user"
#        state: present


    - name: Gather all registered virtual machines
      vmware_vm_info:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        vm_type: vm
        validate_certs: False
      register: vminfo

    - debug: msg="{{ item.guest_name }}"  
      with_items:
       - "{{ vm_info.virtual_machines | json_query(query) }}"
      vars:
        query: "[?'guest_name'=='10.1.32.130-ddcp130']"



